swipe:
  3:
    left:
      command: 'xdotool key alt+Left'
    right:
      command: 'xdotool key alt+Right'
    up:
      command: 'xdotool key ctrl+Tab'
    down:
      command: 'xdotool key ctrl+shift+Tab'
