theme = "monokai"

[editor]
bufferline = "always"
line-number = "relative"
true-color = true
idle-timeout = 0

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = " "
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = " "

[editor.indent-guides]
render = true
character = "┆"
skip-levels = 1

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[keys.normal]
"K" = "hover"
"0" = "goto_line_start"
"$" = "goto_line_end"
"%" = "@mm"
"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"
"G" = "goto_file_end"
"C-tab" = "goto_next_buffer"
"S-C-tab" = "goto_previous_buffer"

[keys.select]
"0" = "goto_line_start"
"$" = "goto_line_end"

[keys.normal.space]
"c" = ":buffer-close"
"e" = "file_picker"
"f" = ":format"
"j" = "goto_previous_buffer"
"k" = "goto_next_buffer"
"q" = "code_action"
"w" = ":write"

[keys.normal."C-w"]
"c" = "wclose"
